services:
  - type: web
    name: staffordmedia-site
    env: node
    repo: https://github.com/RStaff/staffordmedia-site
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_CONTACT_EMAIL
        value: ross@staffordmedia.ai
      - key: NEXT_PUBLIC_CALENDLY_URL
        value: https://calendly.com/ross-stafford
      - key: NEXT_PUBLIC_ABANDO_URL
        value: https://abando.ai
