services:
  - type: web
    name: staffordmedia-site
    env: node
    rootDir: _smc_clean
    envVars:
      - key: NODE_VERSION
        value: 20.19.5
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
    buildCommand: >
      npm ci --include=optional --no-audit --no-fund &&
      npm run build
    startCommand: node .next/standalone/server.js
    autoDeploy: true
