services:
  - type: web
    name: staffordmedia
    env: node
    rootDir: _smc_clean
    buildCommand: npm install --no-audit --no-fund --omit=optional --workspaces=false && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.19.5
