name: Auto-Protect Main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  protect:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      # needed for gh api using GITHUB_TOKEN
      id-token: write

    steps:
      - name: Determine branch
        id: vars
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Apply branch protection (main only)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          BRANCH: ${{ steps.vars.outputs.branch }}
        run: |
          echo "Protecting $BRANCH"
          gh api -X PUT \
            -H "Accept: application/vnd.github+json" \
            repos/$OWNER/$REPO/branches/$BRANCH/protection \
            --input - <<'JSON'
          {
            "required_status_checks": { "strict": true, "contexts": ["CI"] },
            "enforce_admins": true,
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": true,
              "required_approving_review_count": 1,
              "require_code_owner_reviews": false
            },
            "restrictions": null,
            "required_linear_history": true,
            "allow_force_pushes": false,
            "allow_deletions": false,
            "required_conversation_resolution": true
          }
JSON
