name: Auto-label PRs by branch
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const head = context.payload.pull_request.head.ref || '';
            const add = [];
            if (/^site\//.test(head)) add.push('Website Build');
            if (/^llm\//.test(head))  add.push('LLM Dev Work');
            if (add.length) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: add
              });
              core.info(`Added labels: ${add.join(', ')}`);
            } else {
              core.info('No matching prefix; no labels added.');
            }
