name: Auto-Protect Feature Branches
on:
  create:
    branches:
      - feat/**
      - fix/**
      - chore/**
  push:
    branches:
      - feat/**
      - fix/**
      - chore/**
permissions:
  contents: read
  # Needed to change branch protection via API
  administration: write

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Determine branch
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "create" ]]; then
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi

      - name: Apply branch protection
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          BRANCH: ${{ steps.vars.outputs.branch }}
        run: |
          echo "Protecting $BRANCH"
          gh api -X PUT \
            -H "Accept: application/vnd.github+json" \
            repos/$OWNER/$REPO/branches/$BRANCH/protection \
            --input - <<'JSON'
          {
            "required_status_checks": { "strict": true, "contexts": ["CI"] },
            "enforce_admins": true,
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": true,
              "required_approving_review_count": 1,
              "require_code_owner_reviews": false
            },
            "restrictions": null,
            "required_linear_history": true,
            "allow_force_pushes": false,
            "allow_deletions": false,
            "required_conversation_resolution": true
          }
JSON
