name: Context Guard
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const labels = (pr.labels || []).map(l => l.name);
            const hasSite = labels.includes('Website Build');
            const hasLLM  = labels.includes('LLM Dev Work');
            if ((hasSite && hasLLM) || (!hasSite && !hasLLM)) {
              core.setFailed('PR must have exactly one context label: Website Build OR LLM Dev Work.');
            } else {
              core.info('Context label OK.');
            }
