name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: _smc_clean
      working-directory: _smc_clean
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (20.x)
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          check-latest: true
          cache: npm
          cache-dependency-path: _smc_clean/package-lock.json
          cache-dependency-path: _smc_clean/package-lock.json

      - name: Show Node & npm
        run: |
          node -v
          npm -v

      - name: Install (husky-safe)
        run: HUSKY=0 npm ci || HUSKY=0 npm install

      # Non-blocking static checks (report warnings but don't fail deploy)
      - name: Typecheck + Lint (soft)
        run: |
          npm run typecheck || true
          npm run lint || true

      - name: Build (Next.js)
        run: npm run build

      - name: Pull Vercel env (prod)
        run: npx vercel pull --yes --environment=production --token "$VERCEL_TOKEN"

      - name: Vercel build (prod)
        run: npx vercel build --prod --token "$VERCEL_TOKEN"

      - name: Vercel deploy (prebuilt, prod)
        run: npx vercel deploy --prebuilt --prod --token "$VERCEL_TOKEN"
