name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (22.x)
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: Install
        run: |
          HUSKY=0 npm ci || HUSKY=0 npm install

      - name: Build (Next.js)
        run: |
          npm run build

      # Prepare Vercel environment & deploy prod
      - name: Pull Vercel env (prod)
        run: npx vercel pull --yes --environment=production --token "$VERCEL_TOKEN"

      - name: Vercel build (prod)
        run: npx vercel build --prod --token "$VERCEL_TOKEN"

      - name: Vercel deploy (prebuilt, prod)
        run: npx vercel deploy --prebuilt --prod --token "$VERCEL_TOKEN"
