name: Quality

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - 'launch/*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (22.x)
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: |
            package-lock.json
            apps/website/package-lock.json

      - name: Show versions
        run: |
          node -v
          npm -v

      - name: Install (workspaces)
        run: |
          HUSKY=0 npm ci || HUSKY=0 npm install

      - name: Lint + Typecheck + Guard
        run: |
          # try workspace first, then root fallback
          npm run -w apps/website lint || npm run lint || true
          npm run -w apps/website typecheck || npm run typecheck
          npm run -w apps/website guard:headers || npm run guard:headers || true

      - name: Test (allow minimal suites)
        run: |
          npm --workspace apps/website run test || npm test || true

      - name: Build
        run: |
          npm --workspace apps/website run build || npm run build
