name: Quality
on:
  pull_request:
  push:
    branches: ["**"]
permissions: { contents: read }
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
      - name: Install (workspaces)
        run:cd apps/website && HUSKY=0 npm ci --workspaces
      - name: Lint + Typecheck + Guard
        run: npm run -w website check
      - name: Test (allow minimal suites)
        run: npm run -w website test || true
      - name: Build
        run: npm run -w website build

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
  cancel-in-progress: true
