name: Quality
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node (20.x)
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: |
            package-lock.json
            apps/website/package-lock.json

      - name: Install (husky-safe)
        run: |
          HUSKY=0 npm ci || HUSKY=0 npm install

      - name: Lint + Typecheck + Guard
        run: |
          npm run -w apps/website lint || npm run lint || true
          npm run -w apps/website typecheck || npm run typecheck
          npm run -w apps/website guard:headers || npm run guard:headers || true

      - name: Tests (strict enough)
        run: |
          npm --workspace apps/website run test || npm test

      - name: Build (must pass)
        run: |
          npm --workspace apps/website run build || npm run build
